Controllers/GnSoDauBaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLY_HOCSINH.Models;

namespace QLY_HOCSINH.Controllers
{
    public class GnSoDauBaiController : Controller
    {
        private readonly QlyHocSinhContext _context;

        public GnSoDauBaiController(QlyHocSinhContext context)
        {
            _context = context;
        }

        // GET: GnSoDauBai
        public async Task<IActionResult> Index()
        {
            var qlyHocSinhContext = _context.GnSoDauBais.Include(g => g.Lop);
            return View(await qlyHocSinhContext.ToListAsync());
        }

        // GET: GnSoDauBai/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gnSoDauBai = await _context.GnSoDauBais
                .Include(g => g.Lop)
                .FirstOrDefaultAsync(m => m.GnId == id);
            if (gnSoDauBai == null)
            {
                return NotFound();
            }

            return View(gnSoDauBai);
        }

        // GET: GnSoDauBai/Create
        public IActionResult Create()
        {
            ViewData["LopId"] = new SelectList(_context.LopHocs, "LopId", "LopId");
            return View();
        }

        // POST: GnSoDauBai/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GnId,Ngay,Tiet,LopId,TenBai,NoiDung,XepLoai")] GnSoDauBai gnSoDauBai)
        {
            if (ModelState.IsValid)
            {
                _context.Add(gnSoDauBai);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LopId"] = new SelectList(_context.LopHocs, "LopId", "LopId", gnSoDauBai.LopId);
            return View(gnSoDauBai);
        }

        // GET: GnSoDauBai/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gnSoDauBai = await _context.GnSoDauBais.FindAsync(id);
            if (gnSoDauBai == null)
            {
                return NotFound();
            }
            ViewData["LopId"] = new SelectList(_context.LopHocs, "LopId", "LopId", gnSoDauBai.LopId);
            return View(gnSoDauBai);
        }

        // POST: GnSoDauBai/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GnId,Ngay,Tiet,LopId,TenBai,NoiDung,XepLoai")] GnSoDauBai gnSoDauBai)
        {
            if (id != gnSoDauBai.GnId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gnSoDauBai);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GnSoDauBaiExists(gnSoDauBai.GnId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LopId"] = new SelectList(_context.LopHocs, "LopId", "LopId", gnSoDauBai.LopId);
            return View(gnSoDauBai);
        }

        // GET: GnSoDauBai/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gnSoDauBai = await _context.GnSoDauBais
                .Include(g => g.Lop)
                .FirstOrDefaultAsync(m => m.GnId == id);
            if (gnSoDauBai == null)
            {
                return NotFound();
            }

            return View(gnSoDauBai);
        }

        // POST: GnSoDauBai/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gnSoDauBai = await _context.GnSoDauBais.FindAsync(id);
            if (gnSoDauBai != null)
            {
                _context.GnSoDauBais.Remove(gnSoDauBai);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GnSoDauBaiExists(int id)
        {
            return _context.GnSoDauBais.Any(e => e.GnId == id);
        }
    }
}

Controllers/HocSinhController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLY_HOCSINH.Models;

namespace QLY_HOCSINH.Controllers
{
    public class HocSinhController : Controller
    {
        private readonly QlyHocSinhContext _context;

        public HocSinhController(QlyHocSinhContext context)
        {
            _context = context;
        }

        // GET: HocSinh
        public async Task<IActionResult> Index()
        {
            return View(await _context.HocSinhs.ToListAsync());
        }

        // GET: HocSinh/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hocSinh = await _context.HocSinhs
                .FirstOrDefaultAsync(m => m.HsId == id);
            if (hocSinh == null)
            {
                return NotFound();
            }

            return View(hocSinh);
        }

        // GET: HocSinh/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HocSinh/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("HsId,HoTen,Sdt,Diachi,Gioitinh")] HocSinh hocSinh)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hocSinh);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hocSinh);
        }

        // GET: HocSinh/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hocSinh = await _context.HocSinhs.FindAsync(id);
            if (hocSinh == null)
            {
                return NotFound();
            }
            return View(hocSinh);
        }

        // POST: HocSinh/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("HsId,HoTen,Sdt,Diachi,Gioitinh")] HocSinh hocSinh)
        {
            if (id != hocSinh.HsId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hocSinh);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HocSinhExists(hocSinh.HsId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hocSinh);
        }

        // GET: HocSinh/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hocSinh = await _context.HocSinhs
                .FirstOrDefaultAsync(m => m.HsId == id);
            if (hocSinh == null)
            {
                return NotFound();
            }

            return View(hocSinh);
        }

        // POST: HocSinh/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var hocSinh = await _context.HocSinhs.FindAsync(id);
            if (hocSinh != null)
            {
                _context.HocSinhs.Remove(hocSinh);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HocSinhExists(string id)
        {
            return _context.HocSinhs.Any(e => e.HsId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sổ đầu bài</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QLY_HOCSINH.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/gh/eliyantosarage/font-awesome-pro@main/fontawesome-pro-6.5.1-web/css/all.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="https://png.pngtree.com/element_our/png_detail/20181208/notes-icon-png_265236.jpg" type="image/x-icon" />

</head>
<body>
    <header>
        <nav class="navbar navbar-white navbar-primary">
            <div class="container-fluid bg-primary">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#" style="color: #ffffff;">Sổ đầu bài</a>
                </div>

                <ul class="nav navbar-nav">
                    <li>
                        <a class="active" asp-area"" asp-controller="HocSinh" asp-action="Create" style="color: #ffffff;">Thêm học sinh</a>

                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li>
                        <a class="active" asp-area"" asp-controller="LopHoc" asp-action="Create" style="color: #ffffff;">Thêm lớp</a>

                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li>
                        <a class="active" asp-area"" asp-controller="DiemDanhs" asp-action="Create" style="color: #ffffff;">Điểm danh</a>

                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li>
                        <a class="active" asp-area"" asp-controller="GnSoDauBai" asp-action="Create" style="color: #ffffff;">Ghi nhận sổ đầu bài</a>

                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li>
                        <a class="active" style="color: #ffffff;">Mini game</a>

                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="active" asp-area="" asp-controller="GiaoVien" asp-action="DangKy" style="color: #ffffff;">Đăng Ký</a></li>
                    <li>
                        <a class="active " asp-area="" asp-controller="GiaoVien" asp-action="DangNhap" style="color: #ffffff;">Đăng Nhập</a>
                    </li>
                </ul>
            </div>
        </nav>



     
    </header>
    <div class="container body-content">
        <div class="panel panel-primary">
            <div class="panel-heading">
           
            </div>
            <div class="panel-body">    
                    @RenderBody()
            </div>
        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            2024 - Sổ đầu bài - <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>